package identity

import (
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

const agentTypePrefix = "agent"

// TypeID is a type-prefixed UUIDv7 identifier for an agent.
// Format: <prefix>_<crockford-base32-uuidv7>
// Example: agent_01h455vb4pex5vsknk084sn02q
//
// TypeIDs are globally unique, lexicographically sortable by creation time,
// and stable across agent migrations.
//
// Note: the suffix uses Crockford base32 encoding (26 chars). The current
// implementation stores the suffix as an opaque string; full encode/decode
// will be added in a follow-up (see TODO in typeid.go).
type TypeID struct {
	prefix string
	suffix string // Crockford base32-encoded UUIDv7, or raw UUID hex
}

// NewTypeID generates a new TypeID with the "agent" prefix and a fresh UUIDv7.
func NewTypeID() (TypeID, error) {
	id, err := uuid.NewV7()
	if err != nil {
		return TypeID{}, fmt.Errorf("identity: failed to generate UUIDv7: %w", err)
	}
	// TODO: encode id bytes with Crockford base32 for the canonical 26-char suffix.
	return TypeID{prefix: agentTypePrefix, suffix: id.String()}, nil
}

// NewKnowledgeTypeID generates a TypeID with the "ki" (knowledge item) prefix.
func NewKnowledgeTypeID() (TypeID, error) {
	id, err := uuid.NewV7()
	if err != nil {
		return TypeID{}, fmt.Errorf("identity: failed to generate UUIDv7: %w", err)
	}
	return TypeID{prefix: "ki", suffix: id.String()}, nil
}

// ParseTypeID parses a TypeID from its string representation.
// The suffix is stored as-is; no UUID decoding is performed at parse time.
func ParseTypeID(s string) (TypeID, error) {
	parts := strings.SplitN(s, "_", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return TypeID{}, fmt.Errorf("identity: invalid TypeID format: %q", s)
	}
	return TypeID{prefix: parts[0], suffix: parts[1]}, nil
}

// String returns the canonical string representation: prefix_suffix.
func (t TypeID) String() string {
	return t.prefix + "_" + t.suffix
}

// Prefix returns the type prefix (e.g. "agent", "ki").
func (t TypeID) Prefix() string { return t.prefix }

// Time returns the timestamp embedded in the UUIDv7.
// Only valid when the suffix is in standard UUID hex format (as generated by NewTypeID).
// Returns zero time for externally-provided Crockford-base32 suffixes until
// base32 decoding is implemented.
func (t TypeID) Time() time.Time {
	id, err := uuid.Parse(t.suffix)
	if err != nil {
		return time.Time{}
	}
	sec, nsec := id.Time().UnixTime()
	return time.Unix(sec, nsec).UTC()
}
